// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfvsksymnxwprbusskec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mdnNrc3ltbnh3cHJidXNza2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjEzMTgsImV4cCI6MjA2MDYzNzMxOH0.dJQuSERbRl65yy4WWKtJDwJidrQElMPedxZmq7LY6zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);